apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: registry.k8s.io/cloud-provider-ibm/ibm-powervs-block-csi-driver
    newTag: v0.6.0
  - name: registry.k8s.io/sig-storage/csi-provisioner
    newTag: v4.0.0
  - name: registry.k8s.io/sig-storage/csi-attacher
    newTag: v4.5.0
  - name: registry.k8s.io/sig-storage/csi-resizer
    newTag: v1.9.3
  - name: registry.k8s.io/sig-storage/livenessprobe
    newTag: v2.13.0
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newTag: v2.10.0
